# Generated by Django 2.2.24 on 2021-11-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(default='', max_length=100)),
                ('correo', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
