# Generated by Django 2.2.24 on 2021-11-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(related_name='clases', to='estudiantes.Estudiante'),
        ),
        migrations.CreateModel(
            name='InscritosClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clase.Clase')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='inscritos',
            field=models.ManyToManyField(through='clase.InscritosClase', to='estudiantes.Estudiante'),
        ),
    ]
