# Generated by Django 2.2.24 on 2021-11-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('clase', '0002_auto_20211102_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='inscritos',
        ),
        migrations.AddField(
            model_name='clase',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clase', to='estudiantes.Estudiante'),
        ),
        migrations.DeleteModel(
            name='InscritosClase',
        ),
    ]
