# Generated by Django 2.2.24 on 2021-11-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0003_auto_20211103_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='estudiante',
        ),
    ]
