# Generated by Django 2.2.24 on 2021-11-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0004_remove_clase_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='estudiantes',
            new_name='Inscritos',
        ),
        migrations.RenameField(
            model_name='clase',
            old_name='nombre',
            new_name='Materia',
        ),
    ]
